# New Relic Flex Integration Configuration for NetApp ONTAP
# This configuration defines how the Flex integration should run the NetApp monitoring scripts

integrations:
  - name: nri-flex
    config:
      name: netAppSample
      apis:
        # Volume metrics collection
        - name: NetAppVol
          commands:
            - run: /etc/newrelic-infra/integrations.d/NAVol.sh
        
        # Cluster configuration and status
        - name: NetAppCluster
          commands:
            - run: /etc/newrelic-infra/integrations.d/NACluster.sh
        
        # Disk inventory and health
        - name: NetAppDisk
          commands:
            - run: /etc/newrelic-infra/integrations.d/NADisk.sh
        
        # Node health and performance
        - name: NetAppNode
          commands:
            - run: /etc/newrelic-infra/integrations.d/NANode.sh
